ARG BASE_IMAGE="fedora"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

ARG ROOTHOME="/root"
ARG ARCH="x86_64"

RUN dnf install -y \
        sudo \
        git \
        dnf-plugins-core \
        podman \
        skopeo \
        buildah \
    && dnf install -y \
        git-core zsh stow vim tmux screen fzf jq \
        powerline vim-powerline tmux-powerline \
    && dnf install -y \
        'dnf5-command(config-manager)' \
    && dnf clean all \
    && rm -rf /var/cache/yum

# fix for PAM/SSH
RUN chmod 0640 /etc/shadow

USER root

RUN git clone https://github.com/gbraad-dotfiles/upstream.git ${ROOTHOME}/.dotfiles --depth 2\
    && cd ${ROOTHOME}/.dotfiles \
    && . ./zsh/.zshrc.d/dotfiles.zsh \
    && stow config \
    && dotfiles restow

RUN chsh -s /usr/bin/zsh ${USER} \
    && chsh -s /usr/bin/zsh

# install tailscale (or use https://github.com/spotsnel/tailscale-systemd/)
RUN dnf config-manager addrepo --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo \
    && dnf install -y \
        tailscale \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale \
    && systemctl enable tailscaled

# install cloudflared (or use https://github.com/spotsnel/cloudflared-systemd/)
RUN dnf install -y \
        systemd \
    && curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${ARCH}.rpm -o /tmp/cloudflared.rpm \
    && dnf install -y \
        /tmp/cloudflared.rpm \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && rm -f /tmp/cloudflared.rpm
