name: build container - centos-multi-arch
run-name: Building container - centos Multi-Arch

on:
  workflow_dispatch:

jobs:
  build-container-centos-arm64:
    name: build-container-centos-arm64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm

    steps:
      - name: Install missing package
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            podman

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - centos-arm
        run: |
          podman build -t ghcr.io/gbraad-actions/centos:arm64 \
            --build-arg=BASE_IMAGE="quay.io/centos/centos" \
            --build-arg=BASE_VERSION=stream9 \
            --build-arg=ARCH="aarch64" \
            -f containers/Containerfile-centos .

      - name: Run podman save - centos-arm
        run: |
          podman save ghcr.io/gbraad-actions/centos:arm64 \
            --format=oci-dir -o oci-arm64

      - uses: actions/upload-artifact@v4
        with:
          name: oci-arm64
          path: oci-arm64/
          retention-days: 7


  build-container-centos-amd64:
    name: build-container-centos-amd64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run podman build - centos
        run: |
          podman build -t ghcr.io/gbraad-actions/centos:amd64 \
            --build-arg=BASE_IMAGE="quay.io/centos/centos" \
            --build-arg=BASE_VERSION=stream9 \
            -f containers/Containerfile-centos .

      - name: Run podman save - centos
        run: |
          podman save ghcr.io/gbraad-actions/centos:amd64 \
            --format=oci-dir -o oci-amd64

      - uses: actions/upload-artifact@v4
        with:
          name: oci-amd64
          path: oci-amd64/
          retention-days: 7


  push-manifest:
    name: build-container-centos
    needs: 
      - build-container-centos-arm64
      - build-container-centos-amd64
    runs-on: ubuntu-24.04

    steps:
      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: oci-arm64
          path: oci-arm64
      - name: Download amd64
        uses: actions/download-artifact@v4
        with:
          name: oci-amd64
          path: oci-amd64

      - name: Set release tag
        id: get-tag
        run: |
          echo "TAG=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Create manifest
        run: |
          podman manifest create centos-manifest

      - name: Add arm64 to manifest
        run: |
          podman manifest add centos-manifest oci:$(pwd)/oci-arm64
      - name: Add amd64 to manifest
        run: |
          podman manifest add centos-manifest oci:$(pwd)/oci-amd64

      - name: Login to registry
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push container to registry
        run: |
          podman manifest push centos-manifest docker://ghcr.io/gbraad-actions/centos:latest
          podman manifest push centos-manifest docker://ghcr.io/gbraad-actions/centos:stream9
          podman manifest push centos-manifest docker://ghcr.io/gbraad-actions/centos:${{ steps.get-tag.outputs.TAG }}
