name: build process
run-name: Build process

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}
  schedule:
    - cron: "0 0 */2 * *"

jobs:

  trigger-build-container-fedora:
    runs-on: ubuntu-latest
    steps:
      - name: Start Fedora container build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-container-fedora.yml',
              ref: context.ref,
            });
      - name: Wait a little
        run: |
          sleep 10

  wait-for-build-container-fedora:
    runs-on: ubuntu-latest
    needs: trigger-build-container-fedora
    steps:
      - name: Wait for build-container-fedora-amd64 to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          check-name: 'Build and push - Fedora / Build AMD64 / Build Container'
          wait-interval: 10
      - name: Wait for build-container-fedora-arm64 to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          check-name: 'Build and push - Fedora / Build ARM64 / Build Container'
          wait-interval: 10


  trigger-build-container-centos:
    runs-on: ubuntu-latest
    steps:
      - name: Start CentOS container build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-container-centos.yml',
              ref: context.ref,
            });
      - name: Wait a little
        run: |
          sleep 10

  wait-for-build-container-centos:
    runs-on: ubuntu-latest
    needs: trigger-build-container-centos
    steps:
      - name: Wait for build-container-centos-amd64 to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          check-name: 'Build and push - CentOS / Build AMD64 / Build Container'
          wait-interval: 10
      - name: Wait for build-container-centos-arm64 to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          check-name: 'Build and push - CentOS / Build ARM64 / Build Container'
          wait-interval: 10

#  mark-latest-as-stable:
#    runs-on: ubuntu-latest
#    needs:
#      - wait-for-build-container-fedora
#    steps:
#      - name: Trigger mark-latest-as-stable.yml
#        uses: actions/github-script@v7
#        with:
#          script: |
#            await github.rest.actions.createWorkflowDispatch({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              workflow_id: 'mark-latest-as-stable.yml',
#              ref: context.ref,
#            });