name: mark latest as stable - centos
run-name: Mark latest as stable - centos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  mark-as-stable:
    name: mark-as-stable
    uses: ./.github/workflows/reusable-mark-as-stable.yml
    with:
      container_name: "centos"
    secrets: inherit
