name: test stable - fedora
run-name: Test stable - fedora

on:
  workflow_dispatch:

jobs:
  test-stable:
    name: test-stable
    uses: ./.github/workflows/reusable-test-container.yml
    with:
      container_name: "fedora"
      base_version: "stable"
    secrets: inherit
