name: test latest - fedora
run-name: Test latest - fedora

on:
  workflow_dispatch:

jobs:
  test-latest:
    name: test-latest
    uses: ./.github/workflows/reusable-test-container.yml
    with:
      container_name: "fedora"
      base_version: "latest"
    secrets: inherit
